[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide preview pane"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview pane"

[[mgr.prepend_keymap]]
on   = [ "g", "r" ]
run  = "plugin toggle-pane reset"
desc = "Reset pane layout"
