[colors.primary]
background = '#101417'
foreground = '#dfe3e8'

[colors.cursor]
text = '#101417'
cursor = '#dfe3e8'

[colors.vi_mode_cursor]
text = '#101417'
cursor = '#94cdf7'

[colors.search.matches]
foreground = '#41484d'
background = '#cec0e8'

[colors.search.focused_match]
foreground = '#41484d'
background = '#94cdf7'

[colors.footer_bar]
foreground = '#41484d'
background = '#dfe3e8'

[colors.hints.start]
foreground = '#41484d'
background = '#b7c9d8'

[colors.hints.end]
foreground = '#41484d'
background = '#b7c9d8'

[colors.selection]
text = '#c1c7ce'
background = '#41484d'


[colors.normal]
black   = '#41484d'
red     = '#ffb4ab'
green   = '#94cdf7'
yellow  = '#b7c9d8'
blue    = '#cec0e8'
magenta = '#94cdf7'
cyan    = '#b7c9d8'
white   = '#dfe3e8'


[colors.bright]
black   = '#8b9198'
red     = '#ffb4ab'
green   = '#94cdf7'
yellow  = '#b7c9d8'
blue    = '#cec0e8'
magenta = '#94cdf7'
cyan    = '#b7c9d8'
white   = '#dfe3e8'


[colors.dim]
black   = '#41484d'
red     = '#ffb4ab'
green   = '#94cdf7'
yellow  = '#b7c9d8'
blue    = '#cec0e8'
magenta = '#94cdf7'
cyan    = '#b7c9d8'
white   = '#dfe3e8'
