# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  
  boot.initrd.luks.devices."luks-a21ead6e-b2f9-43e5-af86-f73df7fbc25e".device = "/dev/disk/by-uuid/a21ead6e-b2f9-43e5-af86-f73df7fbc25e";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7efb5166-bec4-4223-ada5-d37283fea258";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2876-BF75";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/970" = {
    device = "/dev/disk/by-uuid/b587db24-ee3a-41fe-a9b9-4313a2d849d8";
    fsType = "xfs";
    options = [ "nofail" "x-gvfs-show" ];
  };

  fileSystems."/media/980" = {
    device = "/dev/disk/by-uuid/fc28afba-c612-4bc4-8c41-7d9cdc873dab";
    fsType = "xfs";
    options = [ "nofail" "x-gvfs-show" ];
  };

  fileSystems."/media/WD_BLK" = {
    device = "/dev/disk/by-uuid/15a762e8-ac86-43a8-9445-8047aa22e41d";
    fsType = "xfs";
    options = [ "nofail" "x-gvfs-show" ];
  };

  fileSystems."/media/TEAM" = {
    device = "/dev/disk/by-uuid/3c06f109-6795-472b-a738-e985a7f6f329";
    fsType = "ext4";
    options = [ "nofail" "x-gvfs-show" ];
  };

  fileSystems."/media/MX500" = {
    device = "/dev/disk/by-uuid/b3869d0f-cdf7-48f5-a5fe-edb3f7caa0fb";
    fsType = "ext4";
    options = [ "nofail" "x-gvfs-show" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

