# --- yt-dlp integration ---
ytdl=yes
script-opts=ytdl_hook-ytdl_path=/home/username/.local/bin/yt-dlp

ytdl-raw-options=cookies=/home/username/.config/yt-x/cookies.txt,extractor-args=youtube:player_client=web_safari

# Permissive format so it can fall back (prevents "Requested format not available")
#ytdl-format=best/bestvideo+bestaudio

# Prefer AV1 first, then VP9, then anything
#ytdl-format=bestvideo[vcodec~='av01'][height<=1440]+bestaudio/bestvideo[vcodec~='vp9'][height<=1440]+bestaudio/best[height<=1440]/best
ytdl-format=bestvideo*[height<=1080]+bestaudio/best[height<=1080]/best
# --- Wayland / decode ---
gpu-context=wayland
vo=gpu
hwdec=auto-safe

cache=yes
cache-secs=60
